### ISSUE TITLE
Add Tags to Projects component

### ISSUE THREAD

**Issue by cehicm** [Evil-Bees/evil-bees#16]
We have the Projects component on the Homepage, as well as the Projects page. We want to add tags (like the ones we use on GitHub) to showcase whether the project is labeled as "good first issue", "beginner friendly" , etc.  Here's what they look like, please use the assigned colors.
https://github.com/Evil-Bees/Alertit/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
https://github.com/Evil-Bees/Alertit/issues?q=is%3Aissue+is%3Aopen+label%3Afirst-timers-only

**Comment by AndrewKohn** [comment]
Hi there!  I'm basically a first-timer regarding contributions.  Mind if I take this issue?

**Comment by cehicm** [comment]
Hi @AndrewKohn , please feel free to take it up!
